//
// Copyright © 2024 Antonio Marques. All rights reserved.
//

import Foundation

extension OPCharacter: PreloadablePersistentModel {
    static func preloaded() -> [OPCharacter] {
        let combatant = OPClass.Id(id: "Combatant", system: .OP)
        let specialist = OPClass.Id(id: "Specialist", system: .OP)
        let occultist = OPClass.Id(id: "Occultist", system: .OP)
        let predator = OPClass.Id(id: "Predator", system: .OP)
        return [
            OPCharacter(
                position: .zero,
                names: ["Aurélio", "Jones"],
                player: "",
                icon: Bundle.main.storableImage(path: "Loadables/Characters/Aurelio.jpeg"),
                system: .OP,
                classe: specialist,
                track: OPTrack.Id(id: "Field medic", system: .OP),
                origin: OPOrigin.Id(id: "Academical", system: .OP),
                nex: OPNex(percent: 35),
                movement: 9,
                hitPoints: 28,
                temporaryHitPoints: 0,
                effortPoints: 28,
                sanity: 28,
                attributesTotal: 1,
                attributes: [
                    .AGI: 3, .FOR: 1, .INT: 4, .PRE: 3, .VIG: 1
                ],
                attributeBonuses: [],
                classPowers: specialist.get.powers.filter {
                    $0.id == "Urban Ninja"
                },
                classSkills: [
                ],
                trainingBySkill: [
                    .acrobatics: 0,
                    .animals: 0,
                    .athletics: 10,
                    .arts: 0,
                    .worldliness: 5,
                    .sciences: 0,
                    .crime: 5,
                    .deceiving: 0,
                    .diplomacy: 0,
                    .fortitude: 10,
                    .stealth: 10,
                    .initiative: 0,
                    .intimidation: 0,
                    .intuition: 0,
                    .investigation: 10,
                    .melee: 10,
                    .medicine: 5,
                    .occultism: 10,
                    .perception: 0,
                    .steering: 0,
                    .marksmanship: 10,
                    .profession: 0,
                    .reflexes: 10,
                    .religion: 0,
                    .survival: 0,
                    .tactics: 0,
                    .technology: 5,
                    .will: 10,
                ],
                skillBonuses: [],
                resistances: [],
                rituals: [],
                ammunitions: [],
                weapons: [],
                items: []
            ),
            OPCharacter(
                position: .zero,
                names: ["Gabriel"],
                player: "",
                icon: Bundle.main.storableImage(path: "Loadables/Characters/Gabriel.png"),
                system: .OP,
                classe: combatant,
                track: OPTrack.Id(id: "Infiltrator", system: .OP),
                origin: OPOrigin.Id(id: "Academic", system: .OP),
                nex: OPNex(percent: 35),
                movement: 9,
                hitPoints: 28,
                temporaryHitPoints: 0,
                effortPoints: 28,
                sanity: 28,
                attributesTotal: 1,
                attributes: [
                    .AGI: 3, .FOR: 1, .INT: 4, .PRE: 3, .VIG: 1
                ],
                attributeBonuses: [],
                classPowers: combatant.get.powers.filter {
                    $0.id == "Urban Ninja"
                },
                classSkills: [
                ],
                trainingBySkill: [
                    .acrobatics: 0,
                    .animals: 0,
                    .athletics: 10,
                    .arts: 0,
                    .worldliness: 5,
                    .sciences: 0,
                    .crime: 5,
                    .deceiving: 0,
                    .diplomacy: 0,
                    .fortitude: 10,
                    .stealth: 10,
                    .initiative: 0,
                    .intimidation: 0,
                    .intuition: 0,
                    .investigation: 10,
                    .melee: 10,
                    .medicine: 5,
                    .occultism: 10,
                    .perception: 0,
                    .steering: 0,
                    .marksmanship: 10,
                    .profession: 0,
                    .reflexes: 10,
                    .religion: 0,
                    .survival: 0,
                    .tactics: 0,
                    .technology: 5,
                    .will: 10,
                ],
                skillBonuses: [],
                resistances: [],
                rituals: [],
                ammunitions: [],
                weapons: [],
                items: []
            ),
            OPCharacter(
                position: .zero,
                names: ["Ivanildo", "Grigory"],
                player: "",
                icon: Bundle.main.storableImage(path: "Loadables/Characters/Yuri.png"),
                system: .OP,
                classe: occultist,
                track: OPTrack.Id(id: "Witch", system: .OP),
                origin: OPOrigin.Id(id: "Academic", system: .OP),
                nex: OPNex(percent: 35),
                movement: 9,
                hitPoints: 28,
                temporaryHitPoints: 0,
                effortPoints: 28,
                sanity: 28,
                attributesTotal: 1,
                attributes: [
                    .AGI: 3, .FOR: 1, .INT: 4, .PRE: 3, .VIG: 1
                ],
                attributeBonuses: [],
                classPowers: occultist.get.powers.filter {
                    $0.id == "Urban Ninja"
                },
                classSkills: [
                ],
                trainingBySkill: [
                    .acrobatics: 0,
                    .animals: 0,
                    .athletics: 10,
                    .arts: 0,
                    .worldliness: 5,
                    .sciences: 0,
                    .crime: 5,
                    .deceiving: 0,
                    .diplomacy: 0,
                    .fortitude: 10,
                    .stealth: 10,
                    .initiative: 0,
                    .intimidation: 0,
                    .intuition: 0,
                    .investigation: 10,
                    .melee: 10,
                    .medicine: 5,
                    .occultism: 10,
                    .perception: 0,
                    .steering: 0,
                    .marksmanship: 10,
                    .profession: 0,
                    .reflexes: 10,
                    .religion: 0,
                    .survival: 0,
                    .tactics: 0,
                    .technology: 5,
                    .will: 10,
                ],
                skillBonuses: [],
                resistances: [],
                rituals: [],
                ammunitions: [],
                weapons: [],
                items: []
            ),
            OPCharacter(
                position: .zero,
                names: ["James", "Wyatt"],
                player: "",
                icon: Bundle.main.storableImage(path: "Loadables/Characters/Jimbob.jpeg"),
                system: .OP,
                classe: predator,
                track: OPTrack.Id(id: "Witch", system: .OP),
                origin: OPOrigin.Id(id: "Academic", system: .OP),
                nex: OPNex(percent: 35),
                movement: 9,
                hitPoints: 28,
                temporaryHitPoints: 0,
                effortPoints: 28,
                sanity: 28,
                attributesTotal: 1,
                attributes: [
                    .AGI: 3, .FOR: 1, .INT: 4, .PRE: 3, .VIG: 1
                ],
                attributeBonuses: [],
                classPowers: predator.get.powers.filter {
                    $0.id == "Urban Ninja"
                },
                classSkills: [
                ],
                trainingBySkill: [
                    .acrobatics: 0,
                    .animals: 0,
                    .athletics: 10,
                    .arts: 0,
                    .worldliness: 5,
                    .sciences: 0,
                    .crime: 5,
                    .deceiving: 0,
                    .diplomacy: 0,
                    .fortitude: 10,
                    .stealth: 10,
                    .initiative: 0,
                    .intimidation: 0,
                    .intuition: 0,
                    .investigation: 10,
                    .melee: 10,
                    .medicine: 5,
                    .occultism: 10,
                    .perception: 0,
                    .steering: 0,
                    .marksmanship: 10,
                    .profession: 0,
                    .reflexes: 10,
                    .religion: 0,
                    .survival: 0,
                    .tactics: 0,
                    .technology: 5,
                    .will: 10,
                ],
                skillBonuses: [],
                resistances: [],
                rituals: [],
                ammunitions: [],
                weapons: [],
                items: []
            ),
            OPCharacter(
                position: .zero,
                names: ["Filipa", "Cruz"],
                player: "",
                icon: Bundle.main.storableImage(path: "Loadables/Characters/Pipa.jpeg"),
                system: .OP,
                classe: combatant,
                track: OPTrack.Id(id: "Paranormal Combatant", system: .OP),
                origin: OPOrigin.Id(id: "Inciter of the Paranormal", system: .OP),
                nex: OPNex(percent: 35),
                movement: 9,
                hitPoints: 28,
                temporaryHitPoints: 0,
                effortPoints: 28,
                sanity: 28,
                attributesTotal: 1,
                attributes: [
                    .AGI: 2, .FOR: 3, .INT: 2, .PRE: 2, .VIG: 1
                ],
                attributeBonuses: [],
                classPowers: combatant.get.powers.filter {
                    $0.id == "?"
                },
                classSkills: [
                ],
                trainingBySkill: [
                    .acrobatics: 0,
                    .animals: 0,
                    .athletics: 10,
                    .arts: 0,
                    .worldliness: 5,
                    .sciences: 0,
                    .crime: 5,
                    .deceiving: 0,
                    .diplomacy: 0,
                    .fortitude: 10,
                    .stealth: 10,
                    .initiative: 0,
                    .intimidation: 0,
                    .intuition: 0,
                    .investigation: 10,
                    .melee: 10,
                    .medicine: 5,
                    .occultism: 10,
                    .perception: 0,
                    .steering: 0,
                    .marksmanship: 10,
                    .profession: 0,
                    .reflexes: 10,
                    .religion: 0,
                    .survival: 0,
                    .tactics: 0,
                    .technology: 5,
                    .will: 10,
                ],
                skillBonuses: [],
                resistances: [],
                rituals: [],
                ammunitions: [],
                weapons: [],
                items: []
            ),
            OPCharacter(
                position: .zero,
                names: ["Murilo", "Alcaneda"],
                player: "",
                icon: Bundle.main.storableImage(path: "Loadables/Characters/Murilo.jpeg"),
                graphicalOrientation: .alternative,
                system: .OP,
                classe: specialist,
                track: OPTrack.Id(id: "Infiltrator", system: .OP),
                origin: OPOrigin.Id(id: "Conspiracy theorist", system: .OP),
                nex: OPNex(percent: 35),
                movement: 9,
                hitPoints: 28,
                temporaryHitPoints: 0,
                effortPoints: 28,
                sanity: 28,
                attributesTotal: 1,
                attributes: [
                    .AGI: 3, .FOR: 1, .INT: 4, .PRE: 3, .VIG: 1
                ],
                attributeBonuses: [],
                classPowers: specialist.get.powers.filter {
                    $0.id == "Urban Ninja"
                },
                classSkills: [
                ],
                trainingBySkill: [
                    .acrobatics: 0,
                    .animals: 0,
                    .athletics: 10,
                    .arts: 0,
                    .worldliness: 5,
                    .sciences: 0,
                    .crime: 5,
                    .deceiving: 0,
                    .diplomacy: 0,
                    .fortitude: 10,
                    .stealth: 10,
                    .initiative: 0,
                    .intimidation: 0,
                    .intuition: 0,
                    .investigation: 10,
                    .melee: 10,
                    .medicine: 5,
                    .occultism: 10,
                    .perception: 0,
                    .steering: 0,
                    .marksmanship: 10,
                    .profession: 0,
                    .reflexes: 10,
                    .religion: 0,
                    .survival: 0,
                    .tactics: 0,
                    .technology: 5,
                    .will: 10,
                ],
                skillBonuses: [],
                resistances: [],
                rituals: [],
                ammunitions: [],
                weapons: [],
                items: []
            )
        ]
    }
}
